version: "3.8"
services:
  web:
    build: .
    ports:
      - "3001:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
